### ISSUE TITLE
Improve OAUTH success text 

### ISSUE THREAD

**Issue by TBestLittleHelper** [lichess-org/broadcaster#13]
https://github.com/lichess-org/broadcaster/blob/496ee78de26eb47776e71d866032244ef016cf0f/src-tauri/src/oauth.rs#L78

Just thinking we maybe want to say " Lichess Broadcaster app" and what the "Success " is? You have "logged in" or " authorized the app"?

Maybe even something even simpler? " Lichess Broadcaster is ready to be used! You can close this window and return to the application. For help with getting started read [ link ] or join Discord

**Comment by fitztrev** [comment]
Good suggestion, thanks!

![image](https://github.com/lichess-org/broadcaster/assets/271432/cef655ce-f552-428f-979f-6ed83b487523)
