### ISSUE TITLE
Board order is wrong in the broadcast

### ISSUE THREAD

**Issue by timothyha** [lichess-org/broadcaster#27]
Hi, we've been testing the broadcast app and found that the broadcast board order is often wrong, even though DGT creates headers with board numbers like 1.5 for round 1, board 5.

Please compare https://lichess.dev/broadcast/acc-blitz-and-rapid-june-2024--blitz/round-9/ZRmki9wF (fed from Livechess cloud) with https://lichess.org/broadcast/acc-blitz-and-rapid-june-2024--blitz/round-9/HwEqJSji (fed from the broadcast app). 

Thanks!

**Comment by fitztrev** [comment]
Thanks for the report. Figured out the problem and will have it fixed in the next release.
