### ISSUE TITLE
Unable to login to Lichess Broadcaster

### ISSUE THREAD

**Issue by Baroonn** [lichess-org/broadcaster#33]
Redirect to http://localhost:53940/ after clicking 'Authorize' in the browser returns a 500 error:
![image](https://github.com/user-attachments/assets/34e99e73-78b6-483c-b9e9-413a30c6ad63)
![image](https://github.com/user-attachments/assets/0b7eea96-7411-4359-b8e1-00fe39754bc0)
![image](https://github.com/user-attachments/assets/85c65849-0bb7-409a-81f3-8f156003c5b8)

**Comment by TBestLittleHelper** [comment]
Is this still an issue?
